import { SiteContent } from '@/types/content';

export const deContent: SiteContent = {
  navigation: {
    links: [
      { id: 'about', label: 'Über Uns', href: '#about' },
      { id: 'services', label: 'Leistungen', href: '#services' },
      { id: 'coaching', label: 'Training & Coaching', href: '#training-coaching' },
      { id: 'consulting', label: 'Beratung', href: '#consulting' },
      { id: 'events', label: 'Events & VIP', href: '#events-vip' },
      { id: 'references', label: 'Referenzen', href: '#references' },
      { id: 'media', label: 'Mediathek', href: '#media' },
      { id: 'contact', label: 'Kontakt', href: '#contact' },
    ],
    cta: 'Projekt anfragen',
    switchLang: 'EN',
  },
  hero: {
    eyebrow: 'Mobile Product Genius UG',
    title: 'Mobile Product Genius',
    subtitle: 'Driven by Innovation. Defined by Experience.',
    description:
      'Mit über 15 Jahren internationaler Expertise in der Automobilbranche: wirkungsvolle Produkt und Verkaufstrainings, strategische Beratung sowie exklusive Eventumsetzung für führende globale Marken.',
    ctaPrimary: 'Leistungen entdecken',
    ctaSecondary: 'Kontakt aufnehmen',
    stats: [
      { value: '15+', label: 'Jahre Expertise', sublabel: 'Automobilindustrie weltweit' },
      { value: '25+', label: 'Länder weltweit', sublabel: 'Europa, Nahost, Nordafrika' },
      { value: 'OEM', label: 'Herstellerzertifiziert', sublabel: 'BMW Group & Mercedes-Benz' },
    ],
  },
  about: {
    eyebrow: '',
    title: 'Über Uns',
    subtitle: 'Exzellenz & Leidenschaft',
    paragraphs: [
      'Bei der Mobile Product Genius UG sind wir von Innovation getrieben und durch Erfahrung definiert.',
      'Mit über 15 Jahren internationaler Expertise in der Automobilbranche sind wir spezialisiert auf die Durchführung von wirkungsvollen Produkt und Verkaufstrainings, strategischer Beratung sowie exklusiver Eventumsetzung für führende globale Marken.',
      'Unsere Kernkompetenz liegt darin, Wissen in messbare Performance zu transformieren. Durch innovative Trainingsmethoden, praxisnahes Coaching und ein tiefes Verständnis für Kundenverhalten befähigen wir Verkaufs- und Produktteams sowie das Management, auf höchstem Niveau zu performen.',
      'Über das Training hinaus erwecken wir Marken zum Leben. Von internationalen Automobilmessen bis hin zu exklusiven VIP-Erlebnissen schaffen wir bedeutungsvolle Interaktionen, die Kunden emotional mit der Marke verbinden und jeden Touchpoint nachhaltig prägen.',
      'Wir arbeiten in ganz Europa, dem Nahen Osten und Nordafrika und verbinden globale Standards mit kulturellem Verständnis, um konsistente und hochwertige Ergebnisse zu liefern.',
    ],
    highlight:
      'Bei der Mobile Product Genius UG treibt Innovation alles an – und außergewöhnliche Erlebnisse definieren das Ergebnis.',
    philosophyTitle: 'Unsere Philosophie & Arbeitsweise',
    philosophySubtitle: 'Unsere Arbeit basiert auf klaren Prinzipien:',
    philosophy: [
      {
        title: 'Innovationsgetrieben',
        description: 'Kontinuierliche Weiterentwicklung unserer Methoden.',
      },
      {
        title: 'Kundenfokus',
        description: 'Jeder Schritt schafft Mehrwert für den Kunden.',
      },
      {
        title: 'Performance-orientiert',
        description: 'Messbare Ergebnisse in Vertrieb und Verhalten.',
      },
      {
        title: 'Luxury Mindset',
        description: 'Premium-Standards in Kommunikation und Umsetzung.',
      },
      {
        title: 'Menschliche Verbindung',
        description: 'Vertrauen und langfristige Beziehungen.',
      },
    ],
    strengthsTitle: 'Unsere Stärken',
    strengths: [
      'Über 15 Jahre internationale Automotive-Erfahrung',
      'Bewährte Expertise in Training, Beratung & Event-Execution',
      'Tiefes Verständnis für Premium- und Luxus-Kunden',
      'Starke Zusammenarbeit mit globalen Automobilmarken',
      'Praxisorientierter & ergebnisfokussierter Ansatz',
      'Hohe Professionalität im VIP-Umfeld',
    ],
    imageCaption: 'Internationale Automobilmessen & Keynotes',
    imageSubCaption: 'Jeden Touchpoint in einen nachhaltigen Eindruck verwandeln',
  },
  servicesIntro: {
    eyebrow: 'Maßgeschneiderte Lösungen',
    title: 'Unsere Kernleistungen',
    subtitle:
      'Wir bieten keine Standardlösungen. Wir liefern maßgeschneiderte, ergebnisorientierte Konzepte, die Menschen, Performance und Markenwahrnehmung nachhaltig verbessern.',
    inquireLabel: 'Anfrage stellen',
  },
  services: [
    {
      id: 'training-coaching',
      badge: 'Säule 01',
      title: 'Training & Coaching',
      tagline: 'Wissen in messbare Leistung transformieren',
      intro:
        'Getrieben von Innovation sind unsere Trainings- und Coachingprogramme darauf ausgelegt, Wissen in messbare Leistung umzuwandeln. Wir kombinieren moderne Trainingsmethoden, praxisnahes Coaching und tiefes Produktwissen, um Verkaufsberater, Produktexperten und Führungskräfte auf höchstem Niveau zu entwickeln. Von Produktschulungen über Customer Experience bis hin zu Luxury Mindset – unser Ansatz sorgt für konsistente, souveräne und wirkungsvolle Kundeninteraktionen.',
      outcome: 'Das Ergebnis: gesteigerte Performance und ein Premium-Kundenerlebnis auf höchstem Markenstandard.',
      image: '/assets/images/training-coaching-car.jpg',
      categories: [
        {
          title: 'Produktschulungen',
          items: [
            'Vollständige Produktportfolio-Trainings',
            'Fahr- & digitale Innovationen',
            'E-Mobilitäts-Trainings',
            'Produktlaunch-Trainings',
            'Fahrdynamik & Produkterlebnis',
          ],
        },
        {
          title: 'Verkaufstraining',
          items: [
            'Exzellenz im Verkaufsprozess',
            'Lead-Handling & Qualifizierung',
            'Luxury Mindset Training',
            'Testdrive-Exzellenz',
            'Einwandbehandlung & Abschlussstärke',
          ],
        },
        {
          title: 'Customer Experience Training',
          items: [
            'Premium-Service-Verhalten',
            'Optimierung der Customer Journey',
            'Touchpoint-Qualität',
            'CRM-Training',
          ],
        },
        {
          title: 'Coaching (Teams & Management)',
          items: [
            'On-the-Job Coaching im Showroom',
            'Management- & Führungskräfteentwicklung',
            'Performance-Steuerung',
            'Kommunikations- und Verhaltenscoaching',
          ],
        },
      ],
    },
    {
      id: 'consulting',
      badge: 'Säule 02',
      title: 'Beratung für Automobilhändler',
      tagline: 'Aufbau leistungsstarker Automobilhandelsorganisationen',
      intro:
        'Getrieben von Innovation konzentrieren sich unsere Beratungsleistungen auf den Aufbau leistungsstarker Automobilhandelsorganisationen. Wir analysieren, optimieren und implementieren Strategien entlang von Verkaufsperformance, Teamstruktur und Customer Journey Management. Durch die Kombination aus strategischem Denken und operativer Umsetzung unterstützen wir Management und Vertriebsteams dabei, nachhaltiges Wachstum und operative Exzellenz zu erreichen.',
      outcome: 'Das Ergebnis: intelligente Strukturen, stärkere Teams und Kundenerlebnisse, die Ihre Marke klar differenzieren.',
      image: '/assets/images/consulting-dealership-1.jpg',
      categories: [
        {
          title: 'Sales & Business Performance',
          items: [
            'Optimierung des Sales Funnels',
            'Strukturierung des Lead-Managements',
            'Testdrive-Strategie & Umsetzung',
            'KPI-Steuerung & Performance-Analyse',
          ],
        },
        {
          title: 'Team- & Kommunikationsentwicklung',
          items: [
            'Verbesserung der Zusammenarbeit',
            'Interne Kommunikationsberatung',
            'Coaching für Premium-Standards',
          ],
        },
        {
          title: 'Customer Journey Excellence',
          items: [
            'Touchpoint-Mapping',
            'Experience Design',
            'Prozessoptimierung für Sales & After-Sales',
          ],
        },
        {
          title: 'Onboarding & Recruitment',
          items: [
            'Strukturierte Onboarding-Programme',
            'Unterstützung bei der Rekrutierung von Vertriebsteams',
            'Unterstützung bei Neueröffnungen von Autohäusern',
          ],
        },
      ],
    },
    {
      id: 'events-vip',
      badge: 'Säule 03',
      title: 'Events, Markenerlebnisse & VIP Services',
      tagline: 'Unvergessliche Momente und emotionale Markenbindung',
      intro:
        'Getrieben von Innovation entwickeln wir Automotive-Events und Markenerlebnisse, die weit über klassische Präsentationen hinausgehen. Von internationalen Automobilmessen bis zu exklusiven VIP-Aktivierungen gestalten wir Erlebnisse, die Kunden emotional mit der Marke verbinden. Durch Storytelling, professionelle Produktpräsentationen und hochwertiges Gästemanagement machen wir jede Interaktion zu einem besonderen Moment.',
      outcome: 'Das Ergebnis: starke Markenpräsenz und unvergessliche Erlebnisse mit nachhaltiger Wirkung.',
      image: '/assets/images/event-bmw-i8-delegation.jpg',
      categories: [
        {
          title: 'Event Execution',
          items: [
            'Internationale Automobilmessen & Ausstellungen',
            'Fahrzeug- & Innovationslaunches',
            'Driving Events & Roadshows',
            'Händler- & Kundenaktivierungen',
          ],
        },
        {
          title: 'Produktpräsentation & Moderation',
          items: [
            'Live Präsentationen',
            'Technisches Storytelling',
            'Professionelle Markenkommunikation',
            'Produktkompetenz für Medien & VIP-Gäste',
          ],
        },
        {
          title: 'VIP Handling',
          items: [
            'Premium Hospitality für VIP-Kunden',
            'Exklusive Preview-Erlebnisse',
            'Hochwertiges Gästemanagement',
          ],
        },
        {
          title: 'Experience Design',
          items: [
            'Entwicklung kreativer Konzepte',
            'Planung von Luxury Experiences',
            'Integration digitaler & physischer Touchpoints',
          ],
        },
      ],
    },
  ],
  process: {
    eyebrow: 'Strukturiert & Zielgerichtet',
    title: 'Unser Vorgehen',
    subtitle: 'Vier bewährte Schritte für nachhaltige Exzellenz und planbare Ergebnisse:',
    steps: [
      {
        step: '01',
        title: 'Analyse der Ausgangssituation',
        description: 'Wir verstehen Ihre Ziele, Herausforderungen und Rahmenbedingungen.',
      },
      {
        step: '02',
        title: 'Konzeptentwicklung',
        description: 'Wir entwickeln maßgeschneiderte Lösungen passend zu Ihrer Marke.',
      },
      {
        step: '03',
        title: 'Umsetzung',
        description: 'Wir führen Trainings, Beratung und Events präzise und professionell durch.',
      },
      {
        step: '04',
        title: 'Follow-up & Optimierung',
        description: 'Wir sichern nachhaltige Ergebnisse durch Analyse und Weiterentwicklung.',
      },
    ],
  },
  globalReach: {
    eyebrow: 'Internationale Präsenz',
    title: 'Globale Reichweite',
    subtitle: 'Über 25 Länder – Europa, Nahost und Nordafrika',
    description:
      'Wir arbeiten in ganz Europa, dem Nahen Osten und Nordafrika und unterstützen Hersteller, Importeure und Handelsnetzwerke in über 25 Ländern.',
    subDescription:
      'Unsere internationale Präsenz ermöglicht es uns, globale Standards mit kulturellem Verständnis zu verbinden und in jedem Markt konsistente Qualität und Wirkung zu gewährleisten.',
    headquartersLabel: 'Hauptsitz München · Tätig in 25+ Ländern',
    regions: [
      {
        name: 'Europa',
        description: 'Hersteller-, Importeur- und Handelsnetzwerke.',
      },
      {
        name: 'Naher Osten',
        description: 'Internationale VIP-Events und Repräsentanz.',
      },
      {
        name: 'Nordafrika',
        description: 'Netzwerkunterstützung und Trainingsprogramme.',
      },
    ],
  },
  certifications: {
    eyebrow: 'Akkreditierte Kompetenz',
    title: 'Zertifizierungen & Expertise',
    subtitle: 'Fundierte Qualifikationen nach höchsten Branchen- und Herstellervorgaben:',
    items: [
      'Zertifizierter Sales Trainer',
      'Zertifizierter Produktexperte',
      'Luxury Customer Experience Specialist',
      'Automotive Retail & EV Expertise',
      'Leadership & Coaching Zertifizierungen',
      'Herstellerzertifizierte Trainingserfahrung (BMW Group)',
    ],
    qualificationLabel: 'OEM-Qualifikation',
  },
  references: {
    eyebrow: 'Vertrauen führender Marken',
    title: 'Referenzen',
    subtitle: 'Zusammenarbeit mit Automobilpartnern, Luxus-Hospitality und internationalen Events.',
    automotiveTitle: 'Automobilpartner',
    automotivePartners: [
      'BMW Group Deutschland',
      'BMW Group Schweiz',
      'BMW Group Middle East',
      'BMW North Africa',
      'Mercedes-Benz Deutschland',
      'BYD Europe',
      'Rolls-Royce Iraq',
      'Mazda Iraq',
    ],
    automotiveFooter: 'OEM & Handelsnetzwerke',
    hospitalityTitle: 'Luxus-Hospitality',
    hospitalityPartners: [
      'Mandarin Oriental München',
      'Kempinski Hotel München',
    ],
    hospitalityFooter: 'Luxury Hospitality Standards',
    eventsTitle: 'Wichtige Events',
    majorEvents: [
      'Concorso d\'Eleganza Villa d\'Este',
      'IAA Frankfurt & IAA München',
      'Geneva International Motor Show',
      'Qatar Geneva Motor Show',
      'Dubai International Motor Show',
    ],
    eventsFooter: 'Internationale Ausstellungen',
    vipTitle: 'VIP-Gäste',
    vipIntro:
      'Wir hatten das Privileg, mit hochrangigen Persönlichkeiten aus Politik, Wirtschaft, Sport und Kunst zu arbeiten, darunter:',
    vipGuests: [
      'Seine Hoheit Sheikh Tamim bin Hamad Al Thani',
      'Seine Hoheit Sheikh Mansoor bin Mohammed bin Rashid Al Maktoum',
      'Seine Hoheit Sheikh Ahmad bin Mohammed bin Rashid Al Maktoum',
      'Jeff Koons',
      'Gianni Infantino',
      'Rowan Atkinson',
      'Jean Todt',
    ],
    vipOutro:
      'Diese Erfahrungen spiegeln unsere Fähigkeit wider, auf höchstem Niveau mit Professionalität, Diskretion und Markenrepräsentation zu agieren.',
  },
  media: {
    eyebrow: 'Mediathek',
    title: 'Medien',
    subtitle: 'Erleben Sie unsere Arbeit in Aktion',
    description:
      'Unsere Mediathek zeigt reale Eindrücke aus internationalen Automotive-Events, Produkttrainings, Präsentationen und VIP-Erlebnissen. Diese Einblicke spiegeln Qualität, Energie und Professionalität wider.',
    filters: {
      all: 'Alle',
      training: 'Training & Coaching',
      events: 'Events',
    },
    categoryLabels: {
      training: 'Training & Coaching',
      events: 'Events',
    },
    playLabel: 'Video abspielen',
    viewLabel: 'Ansicht öffnen',
    items: [
      {
        id: 'vid-1',
        title: 'Event Video I',
        category: 'events',
        type: 'video',
        src: '/assets/videos/mprog-video-1.mp4',
        thumbnail: '/assets/images/hero-saidi-bmw7.jpg',
        description: 'Einblicke in internationale Automotive-Events und VIP-Präsentationen.',
      },
      {
        id: 'vid-2',
        title: 'Training Video II',
        category: 'training',
        type: 'video',
        src: '/assets/videos/mprog-video-2.mp4',
        thumbnail: '/assets/images/training-group.jpg',
        description: 'Impressionen aus praxisorientierten Trainings- und Coaching-Sessions.',
      },
      {
        id: 'img-hero-saidi',
        title: 'Produktpräsentation',
        category: 'events',
        type: 'image',
        src: '/assets/images/hero-saidi-bmw7.jpg',
        description: 'Keynote und Live-Produktpräsentation.',
      },
      {
        id: 'img-event-gims',
        title: 'Genfer Autosalon',
        category: 'events',
        type: 'image',
        src: '/assets/images/event-bmw-genius-gims.jpg',
        description: 'Internationale Markenrepräsentation als Product Genius auf der GIMS.',
      },
      {
        id: 'img-bmw-i8',
        title: 'Delegation & Präsentation',
        category: 'events',
        type: 'image',
        src: '/assets/images/event-bmw-i8-delegation.jpg',
        description: 'Produktvorstellung und Betreuung bei VIP-Delegationen.',
      },
      {
        id: 'img-stage-keynote',
        title: 'Bühnenpräsentation',
        category: 'events',
        type: 'image',
        src: '/assets/images/event-keynote-stage.jpg',
        description: 'Moderation und Markenkommunikation auf der Hauptbühne.',
      },
      {
        id: 'img-event-atmosphere',
        title: 'Messe-Atmosphäre',
        category: 'events',
        type: 'image',
        src: '/assets/images/event-atmosphere-wide.jpg',
        description: 'Eindrücke internationaler Automobilausstellungen.',
      },
      {
        id: 'img-bmw7-vip',
        title: 'VIP Präsentation',
        category: 'events',
        type: 'image',
        src: '/assets/images/event-bmw7-vip.jpg',
        description: 'Produktkompetenz und exklusives Gästemanagement.',
      },
      {
        id: 'img-hospitality',
        title: 'VIP Hospitality',
        category: 'events',
        type: 'image',
        src: '/assets/images/event-vip-hospitality.jpg',
        description: 'Premium Hospitality für VIP-Gäste.',
      },
      {
        id: 'img-training-xm',
        title: 'Produktschulung',
        category: 'training',
        type: 'image',
        src: '/assets/images/training-bmw-xm.jpg',
        description: 'Fahrdynamik und Produkterlebnis im Training.',
      },
      {
        id: 'img-training-coaching',
        title: 'Showroom Coaching',
        category: 'training',
        type: 'image',
        src: '/assets/images/training-coaching-car.jpg',
        description: 'On-the-job Coaching und fahrzeugnahe Schulung.',
      },
      {
        id: 'img-training-classroom',
        title: 'Workshop & Schulung',
        category: 'training',
        type: 'image',
        src: '/assets/images/training-classroom.jpg',
        description: 'Interaktive Methodik im Schulungsraum.',
      },
      {
        id: 'img-training-group',
        title: 'Team-Training',
        category: 'training',
        type: 'image',
        src: '/assets/images/training-group.jpg',
        description: 'Verkaufs- und Produkttraining in der Gruppe.',
      },
      {
        id: 'img-training-connecteddrive',
        title: 'Digitale Innovationen',
        category: 'training',
        type: 'image',
        src: '/assets/images/training-connecteddrive.jpg',
        description: 'Digitale Features und Kundeninteraktion.',
      },
      {
        id: 'img-consulting-dealership',
        title: 'Händlerberatung',
        category: 'training',
        type: 'image',
        src: '/assets/images/consulting-dealership-1.jpg',
        description: 'Optimierung von Handelsabläufen und Touchpoints.',
      },
    ],
  },
  contact: {
    eyebrow: 'Kontakt',
    title: 'Kontakt',
    subtitle: 'Lassen Sie uns zusammenarbeiten',
    description:
      'Ob Sie Ihr Vertriebsteam stärken, Ihr Kundenerlebnis verbessern oder Ihre Retail-Strategie optimieren möchten: Mobile Product Genius UG ist Ihr Partner für nachhaltigen Erfolg.',
    companyName: 'Mobile Product Genius UG',
    addressLine1: 'Ruth-Drexel-Strasse 17',
    addressLine2: '81927 München',
    addressCity: 'Deutschland',
    email: 'info@mprog.eu',
    website: 'www.mprog.eu',
    headquartersLabel: 'Unternehmenssitz',
    emailLabel: 'Direkter Kontakt',
    websiteLabel: 'Webportal',
    formTitle: 'Senden Sie uns Ihre Anfrage',
    formSubtitle: 'Senden Sie uns Ihre Anforderungen – wir melden uns persönlich bei Ihnen.',
    successTitle: 'Anfrage erfolgreich übermittelt',
    sendAnotherButton: 'Weitere Nachricht senden',
    form: {
      nameLabel: 'Ihr vollständiger Name',
      namePlaceholder: 'z.B. Maximilian Mustermann',
      emailLabel: 'Ihre E-Mail-Adresse',
      emailPlaceholder: 'name@unternehmen.de',
      companyLabel: 'Unternehmen / Organisation',
      companyPlaceholder: 'z.B. Autohaus Gruppe / Automobilhersteller',
      serviceLabel: 'Gewünschte Leistung',
      serviceOptions: {
        all: 'Bitte wählen Sie einen Bereich',
        training: 'Training & Coaching',
        consulting: 'Beratung für Automobilhändler',
        events: 'Events, Markenerlebnisse & VIP Services',
        general: 'Allgemeine Anfrage',
      },
      messageLabel: 'Ihre Nachricht / Projektvorhaben',
      messagePlaceholder: 'Beschreiben Sie kurz Ihr Anliegen oder geplante Termine...',
      submitButton: 'Nachricht absenden',
      submittingButton: 'Wird übermittelt...',
      successMessage: 'Vielen Dank für Ihre Anfrage. Wir werden uns persönlich bei Ihnen melden.',
      errorMessage: 'Bitte füllen Sie alle erforderlichen Felder aus.',
    },
  },
  footer: {
    tagline: 'Driven by Innovation. Defined by Experience.',
    description: '',
    navigationTitle: 'Navigation',
    servicesTitle: 'Leistungen',
    serviceLinks: [
      { label: 'Produkt- & EV-Training', href: '#training-coaching' },
      { label: 'Verkaufstraining & Luxury Mindset', href: '#training-coaching' },
      { label: 'Showroom- & Management-Coaching', href: '#training-coaching' },
      { label: 'Automotive Retail Beratung', href: '#consulting' },
      { label: 'Events & Moderation', href: '#events-vip' },
      { label: 'VIP Handling & Hospitality', href: '#events-vip' },
    ],
    contactTitle: 'Kontakt Information',
    allRightsReserved: 'Alle Rechte vorbehalten.',
    privacy: 'Datenschutz',
    imprint: 'Impressum',
    backToTop: 'Nach oben',
    imprintTitle: 'Impressum & Rechtliche Angaben',
    imprintContent: {
      legalHeading: 'Angaben gemäß § 5 TMG:',
      contactHeading: 'Kontakt:',
      managementHeading: 'Vertretungsberechtigte Geschäftsführung:',
      contentResponsibleHeading: 'Verantwortlich für den Inhalt nach § 55 Abs. 2 RStV:',
      managementName: 'Mobile Product Genius UG',
      contentResponsible: 'Mobile Product Genius UG, Ruth-Drexel-Strasse 17, 81927 München',
    },
  },
};
