import { SiteContent } from '@/types/content';

export const enContent: SiteContent = {
  navigation: {
    links: [
      { id: 'about', label: 'About Us', href: '#about' },
      { id: 'services', label: 'Services', href: '#services' },
      { id: 'coaching', label: 'Training & Coaching', href: '#training-coaching' },
      { id: 'consulting', label: 'Consulting', href: '#consulting' },
      { id: 'events', label: 'Events & VIP', href: '#events-vip' },
      { id: 'references', label: 'References', href: '#references' },
      { id: 'media', label: 'Media', href: '#media' },
      { id: 'contact', label: 'Contact', href: '#contact' },
    ],
    cta: 'Inquire Project',
    switchLang: 'DE',
  },
  hero: {
    eyebrow: 'Mobile Product Genius UG',
    title: 'Mobile Product Genius',
    subtitle: 'Driven by Innovation. Defined by Experience.',
    description:
      'With over 15 years of international expertise in the automotive industry, we specialise in delivering high-impact product and sales training, strategic consulting and premium event execution for leading global brands.',
    ctaPrimary: 'Explore Services',
    ctaSecondary: 'Get in Touch',
    stats: [
      { value: '15+', label: 'Years Experience', sublabel: 'Automotive industry globally' },
      { value: '25+', label: 'Countries', sublabel: 'Europe, Middle East, North Africa' },
      { value: 'OEM', label: 'OEM Certified', sublabel: 'BMW Group & Mercedes-Benz' },
    ],
  },
  about: {
    eyebrow: 'Excellence & Experience',
    title: 'About Us',
    paragraphs: [
      'At Mobile Product Genius, we are driven by innovation and defined by experience.',
      'With over 15 years of international expertise in the automotive industry, we specialise in delivering high-impact product and sales training, strategic consulting and premium event execution for leading global brands.',
      'Our core strength lies in transforming knowledge into performance. Through innovative training methods, practical coaching and a deep understanding of customer behaviour, we empower sales teams, product experts and management to perform at the highest level.',
      'Beyond training, we bring brands to life. From international motor shows to exclusive VIP experiences, we create meaningful interactions that connect customers emotionally with the brand and turn every touchpoint into a lasting impression.',
      'We work across Europe, the Middle East, and North Africa, combining global standards with cultural understanding to deliver consistent, high-quality results.',
    ],
    highlight:
      'At Mobile Product Genius UG, innovation drives everything we do and exceptional experiences define the outcome.',
    philosophyTitle: 'Our Philosophy & Approach',
    philosophySubtitle: 'Our work is guided by clear principles:',
    philosophy: [
      {
        title: 'Innovation-driven',
        description:
          'We continuously evolve our methods to match market developments & customer expectations.',
      },
      {
        title: 'Customer-centric',
        description:
          'Every action is designed to create value for the customer.',
      },
      {
        title: 'Performance-focused',
        description:
          'We deliver measurable improvements in sales, behaviour & experience.',
      },
      {
        title: 'Luxury mindset',
        description:
          'We apply luxury standards in communication, behaviour & execution.',
      },
      {
        title: 'Human connection',
        description:
          'We build trust, engagement & long-term relationships.',
      },
    ],
    strengthsTitle: 'Key Strengths',
    strengths: [
      'Over 15 years of international automotive experience',
      'Proven expertise in training, consulting & premium event execution',
      'Deep understanding of luxury customer expectations',
      'Strong track record with global automotive brands',
      'Hands-on, practical & results-oriented approach',
      'High level of professionalism in VIP environments',
    ],
    imageCaption: 'International Motor Shows & Keynotes',
    imageSubCaption: 'Turning every touchpoint into a lasting impression',
  },
  servicesIntro: {
    eyebrow: 'Tailored Solutions',
    title: 'Our Core Services',
    subtitle:
      'We don\'t offer standard solutions. We deliver tailored, results-driven concepts that elevate people, performance and brand perception.',
    inquireLabel: 'Inquire now',
  },
  services: [
    {
      id: 'training-coaching',
      badge: 'Pillar 01',
      title: 'Training & Coaching',
      tagline: 'Transforming knowledge into measurable performance',
      intro:
        'Driven by innovation, our training and coaching programs are designed to transform knowledge into measurable performance. We combine modern training methodologies, hands-on coaching, and deep product expertise to empower sales teams, product specialists, and management to perform at the highest level. From product training to customer experience and luxury mindset, our approach ensures that every interaction is consistent, confident, and impactful.',
      outcome: 'The result: elevated performance and a premium customer experience that reflects the highest brand standards.',
      image: '/assets/images/training-coaching-car.jpg',
      categories: [
        {
          title: 'Product Training',
          items: [
            'Full product portfolio training',
            'Driving & digital innovations',
            'EV training',
            'Product launch training',
            'Driving dynamics & product experience',
          ],
        },
        {
          title: 'Sales Training',
          items: [
            'Sales process excellence',
            'Lead handling & qualification',
            'Luxury mindset training',
            'Test-drive excellence',
            'Objection handling & closing',
          ],
        },
        {
          title: 'Customer Experience Training',
          items: [
            'Premium service behaviours',
            'Customer journey optimisation',
            'Touchpoint quality',
            'CRM training',
          ],
        },
        {
          title: 'Coaching (Teams & Management)',
          items: [
            'On-the-job coaching in the showroom',
            'Management coaching & leadership development',
            'Performance steering',
            'Behavioural and communication coaching',
          ],
        },
      ],
    },
    {
      id: 'consulting',
      badge: 'Pillar 02',
      title: 'Consulting for Automotive Retailers',
      tagline: 'Building high-performing automotive retail organisations',
      intro:
        'Driven by innovation, our consulting services focus on building high-performing automotive retail organisations. We analyse, optimise, and implement strategies across sales performance, team collaboration and customer journey management. Through a combination of strategic thinking and practical execution, we support management and sales teams in achieving sustainable growth and operational excellence.',
      outcome: 'The result: intelligent structures, stronger teams, and customer experiences that truly differentiate your brand.',
      image: '/assets/images/consulting-dealership-1.jpg',
      categories: [
        {
          title: 'Sales & Business Performance',
          items: [
            'Sales funnel optimisation',
            'Lead management restructuring',
            'Test-drive strategy & implementation',
            'KPI steering & performance analysis',
          ],
        },
        {
          title: 'Team Development & Communication',
          items: [
            'Collaboration improvement',
            'Internal communication consulting',
            'Coaching for consistent premium standards',
          ],
        },
        {
          title: 'Customer Journey Excellence',
          items: [
            'Touchpoint mapping',
            'Experience design',
            'Process optimisation for sales & aftersales',
          ],
        },
        {
          title: 'Onboarding & Recruitment',
          items: [
            'Structured onboarding programmes',
            'Recruitment support for sales teams',
            'New dealership opening support',
          ],
        },
      ],
    },
    {
      id: 'events-vip',
      badge: 'Pillar 03',
      title: 'Events, Brand Experiences & VIP Services',
      tagline: 'Creating powerful brand presence and lasting impressions',
      intro:
        'Driven by innovation, we create automotive events and brand experiences that go beyond traditional presentations. From international motor shows to exclusive VIP activations, we design and deliver experiences that connect customers emotionally with the brand. Through expert storytelling, product presentation, and premium guest handling, we turn every interaction into a memorable moment.',
      outcome: 'The result: powerful brand presence and unforgettable experiences that leave a lasting impression.',
      image: '/assets/images/event-bmw-i8-delegation.jpg',
      categories: [
        {
          title: 'Event Execution',
          items: [
            'International auto shows & exhibitions',
            'New vehicle & innovation launches',
            'Driving events & roadshows',
            'Dealer & customer activation events',
          ],
        },
        {
          title: 'Product Presentation & Moderation',
          items: [
            'Live presentations',
            'Technical storytelling',
            'Professional brand communication',
            'Product expertise for media & VIP customers',
          ],
        },
        {
          title: 'VIP Handling',
          items: [
            'Premium hospitality for VIP clients',
            'Exclusive preview experiences',
            'High-level guest hosting & management',
          ],
        },
        {
          title: 'Experience Design',
          items: [
            'Creative concept development',
            'Luxury experience planning',
            'Integration of digital & physical brand touchpoints',
          ],
        },
      ],
    },
  ],
  process: {
    eyebrow: 'How We Work (Process Overview)',
    title: 'How We Work',
    subtitle: 'Our proven 4-stage process:',
    steps: [
      {
        step: '01',
        title: 'Understanding Your Needs',
        description: 'We analyse your current situation, challenges & objectives.',
      },
      {
        step: '02',
        title: 'Concept Development',
        description: 'We design a tailored solution aligned with your brand & goals.',
      },
      {
        step: '03',
        title: 'Implementation',
        description: 'We deliver training, consulting and event execution with precision and consistency.',
      },
      {
        step: '04',
        title: 'Follow-Up & Performance Review',
        description: 'We ensure sustainable results through evaluation & continuous improvement.',
      },
    ],
  },
  globalReach: {
    eyebrow: 'International Presence',
    title: 'Global Reach',
    subtitle: 'More than 25 countries across Europe, Middle East & North Africa',
    description:
      'We operate across Europe, the Middle East and North Africa, supporting manufacturers, importers and retail networks in more than 25 countries.',
    subDescription:
      'Our international presence allows us to combine global standards with cultural understanding, ensuring consistent quality, relevance, and impact in every market.',
    headquartersLabel: 'Munich Headquarters · Operating in 25+ Countries',
    regions: [
      {
        name: 'Europe',
        description: 'Manufacturer, importer and retail network support.',
      },
      {
        name: 'Middle East',
        description: 'VIP activations, brand representation and high-profile events.',
      },
      {
        name: 'North Africa',
        description: 'Dealership training, product launches and network development.',
      },
    ],
  },
  certifications: {
    eyebrow: 'Accredited Expertise',
    title: 'Certifications & Expertise',
    subtitle: 'Recognised industry standards and manufacturer credentials:',
    items: [
      'Certified Sales Trainer',
      'Certified Product Expert',
      'Luxury Customer Experience Specialist',
      'Automotive Retail & EV Expertise',
      'Leadership & Coaching Certifications',
      'Manufacturer-certified training experience (BMW Group, Mercedes-Benz)',
    ],
    qualificationLabel: 'OEM Qualification',
  },
  references: {
    eyebrow: 'Trusted by Leaders',
    title: 'References',
    subtitle: 'Automotive partners, luxury hospitality and major events.',
    automotiveTitle: 'Automotive Partners',
    automotivePartners: [
      'BMW Group Germany',
      'BMW Group Switzerland',
      'BMW Group Middle East',
      'BMW North Africa',
      'Mercedes-Benz Germany',
      'Rolls-Royce Iraq',
      'Mazda Iraq',
      'BYD Europe',
    ],
    automotiveFooter: 'OEM & Retail Networks',
    hospitalityTitle: 'Luxury Hospitality',
    hospitalityPartners: [
      'Mandarin Oriental Munich',
      'Kempinski Hotel Munich',
    ],
    hospitalityFooter: 'Luxury Hospitality Standards',
    eventsTitle: 'Major Events',
    majorEvents: [
      'Concorso d\'Eleganza Villa d\'Este',
      'IAA Frankfurt & IAA Munich',
      'Geneva International Motor Show',
      'Qatar Geneva Motor Show',
      'Dubai International Motor Show',
    ],
    eventsFooter: 'International Exhibitions',
    vipTitle: 'VIP Guests Hosted',
    vipIntro:
      'We have had the privilege of working with high-profile personalities from politics, business, sports, and the arts, including:',
    vipGuests: [
      'His Highness Sheikh Tamim bin Hamad Al Thani',
      'His Highness Sheikh Mansoor bin Mohammed bin Rashid Al Maktoum',
      'His Highness Sheikh Ahmad bin Mohammed bin Rashid Al Maktoum',
      'Jeff Koons',
      'Gianni Infantino',
      'Rowan Atkinson',
      'Jean Todt',
    ],
    vipOutro:
      'These experiences reflect our ability to operate at the highest level of professionalism, discretion and brand representation.',
  },
  media: {
    eyebrow: 'Media',
    title: 'Media',
    subtitle: 'Experience our work in action',
    description:
      'Our media section showcases real moments from international automotive events, product presentations, training sessions and VIP experiences. From global motor shows to exclusive brand activations, these insights reflect the quality, energy and professionalism we bring to every project.',
    filters: {
      all: 'All',
      training: 'Training & Coaching',
      events: 'Events',
    },
    categoryLabels: {
      training: 'Training & Coaching',
      events: 'Events',
    },
    playLabel: 'Play video',
    viewLabel: 'View image',
    items: [
      {
        id: 'vid-1',
        title: 'Event Video I',
        category: 'events',
        type: 'video',
        src: '/assets/videos/mprog-video-1.mp4',
        thumbnail: '/assets/images/hero-saidi-bmw7.jpg',
        description: 'Insights from international automotive events and VIP presentations.',
      },
      {
        id: 'vid-2',
        title: 'Training Video II',
        category: 'training',
        type: 'video',
        src: '/assets/videos/mprog-video-2.mp4',
        thumbnail: '/assets/images/training-group.jpg',
        description: 'Impressions from hands-on training and sales coaching sessions.',
      },
      {
        id: 'img-hero-saidi',
        title: 'Product Presentation',
        category: 'events',
        type: 'image',
        src: '/assets/images/hero-saidi-bmw7.jpg',
        description: 'Keynote and live vehicle presentation.',
      },
      {
        id: 'img-event-gims',
        title: 'Geneva International Motor Show',
        category: 'events',
        type: 'image',
        src: '/assets/images/event-bmw-genius-gims.jpg',
        description: 'Global brand representation as BMW Product Genius at GIMS.',
      },
      {
        id: 'img-bmw-i8',
        title: 'Delegation & Presentation',
        category: 'events',
        type: 'image',
        src: '/assets/images/event-bmw-i8-delegation.jpg',
        description: 'Product presentation during VIP delegation visit.',
      },
      {
        id: 'img-stage-keynote',
        title: 'Keynote Presentation',
        category: 'events',
        type: 'image',
        src: '/assets/images/event-keynote-stage.jpg',
        description: 'Stage moderation and brand communication.',
      },
      {
        id: 'img-event-atmosphere',
        title: 'Show Atmosphere',
        category: 'events',
        type: 'image',
        src: '/assets/images/event-atmosphere-wide.jpg',
        description: 'Impressions from international motor shows.',
      },
      {
        id: 'img-bmw7-vip',
        title: 'VIP Presentation',
        category: 'events',
        type: 'image',
        src: '/assets/images/event-bmw7-vip.jpg',
        description: 'Product expertise and VIP guest hosting.',
      },
      {
        id: 'img-hospitality',
        title: 'VIP Hospitality',
        category: 'events',
        type: 'image',
        src: '/assets/images/event-vip-hospitality.jpg',
        description: 'Premium hospitality for VIP clients.',
      },
      {
        id: 'img-training-xm',
        title: 'Product Training',
        category: 'training',
        type: 'image',
        src: '/assets/images/training-bmw-xm.jpg',
        description: 'Driving dynamics and vehicle tech training.',
      },
      {
        id: 'img-training-coaching',
        title: 'Showroom Coaching',
        category: 'training',
        type: 'image',
        src: '/assets/images/training-coaching-car.jpg',
        description: 'Hands-on showroom and in-vehicle coaching.',
      },
      {
        id: 'img-training-classroom',
        title: 'Workshop & Classroom',
        category: 'training',
        type: 'image',
        src: '/assets/images/training-classroom.jpg',
        description: 'Interactive classroom training methodology.',
      },
      {
        id: 'img-training-group',
        title: 'Team Training',
        category: 'training',
        type: 'image',
        src: '/assets/images/training-group.jpg',
        description: 'Group sales and product training session.',
      },
      {
        id: 'img-training-connecteddrive',
        title: 'Digital Innovations',
        category: 'training',
        type: 'image',
        src: '/assets/images/training-connecteddrive.jpg',
        description: 'Digital features and customer experience.',
      },
      {
        id: 'img-consulting-dealership',
        title: 'Dealership Consulting',
        category: 'training',
        type: 'image',
        src: '/assets/images/consulting-dealership-1.jpg',
        description: 'Showroom processes and retail touchpoint analysis.',
      },
    ],
  },
  contact: {
    eyebrow: 'Contact',
    title: 'Contact',
    subtitle: 'Let\'s Work Together',
    description:
      'Whether you want to enhance your sales team, improve your customer experience, or optimise your retail strategy: Mobile Product Genius UG is your partner for long-term success.',
    companyName: 'Mobile Product Genius UG',
    addressLine1: 'Ruth-Drexel-Strasse 17',
    addressLine2: '81927 München',
    addressCity: 'Germany',
    email: 'info@mprog.eu',
    website: 'www.mprog.eu',
    headquartersLabel: 'Headquarters',
    emailLabel: 'Direct Contact',
    websiteLabel: 'Web',
    formTitle: 'Send Us Your Inquiry',
    formSubtitle: 'Send us your requirements – we will get back to you personally.',
    successTitle: 'Inquiry Successfully Submitted',
    sendAnotherButton: 'Send Another Message',
    form: {
      nameLabel: 'Full Name',
      namePlaceholder: 'e.g. John Doe',
      emailLabel: 'Email Address',
      emailPlaceholder: 'name@company.com',
      companyLabel: 'Company / Organization',
      companyPlaceholder: 'e.g. Dealership Group / Automotive Brand',
      serviceLabel: 'Area of Interest',
      serviceOptions: {
        all: 'Please select an area',
        training: 'Training & Coaching',
        consulting: 'Consulting for Automotive Retailers',
        events: 'Events, Brand Experiences & VIP Services',
        general: 'General Inquiry',
      },
      messageLabel: 'Your Message',
      messagePlaceholder: 'Briefly describe your requirements or inquiry...',
      submitButton: 'Send Message',
      submittingButton: 'Submitting...',
      successMessage: 'Thank you for your inquiry. We will get in touch with you personally.',
      errorMessage: 'Please fill in all required fields.',
    },
  },
  footer: {
    tagline: 'Driven by Innovation. Defined by Experience.',
    description:
      'Over 15 years of international expertise in automotive training, dealership consulting and VIP event execution across Europe, the Middle East and North Africa.',
    navigationTitle: 'Navigation',
    servicesTitle: 'Services',
    serviceLinks: [
      { label: 'Product & EV Training', href: '#training-coaching' },
      { label: 'Sales Training & Luxury Mindset', href: '#training-coaching' },
      { label: 'Showroom & Management Coaching', href: '#training-coaching' },
      { label: 'Automotive Retail Consulting', href: '#consulting' },
      { label: 'Events & Moderation', href: '#events-vip' },
      { label: 'VIP Handling & Hospitality', href: '#events-vip' },
    ],
    contactTitle: 'Contact Information',
    allRightsReserved: 'All rights reserved.',
    privacy: 'Privacy Policy',
    imprint: 'Legal Notice / Imprint',
    backToTop: 'Back to top',
    imprintTitle: 'Legal Notice & Information',
    imprintContent: {
      legalHeading: 'Information pursuant to § 5 TMG:',
      contactHeading: 'Contact:',
      managementHeading: 'Authorised Managing Director:',
      contentResponsibleHeading: 'Responsible for content pursuant to § 55 Para. 2 RStV:',
      managementName: 'Mobile Product Genius UG',
      contentResponsible: 'Mobile Product Genius UG, Ruth-Drexel-Strasse 17, 81927 München',
    },
  },
};
